---
Name: nswdpc_recaptchav3_spamprotection
---
NSWDPC\SpamProtection\TokenResponse:
  # 1 = good, 0 = spam
  score: 0.5
NSWDPC\SpamProtection\Verifier:
  # Provided by the Recaptcha admin project
  secret_key: ''
NSWDPC\SpamProtection\RecaptchaV3Field:
  # Provided by the Recaptcha admin project
  site_key: ''
  # Global action prefix for the field
  execute_action: 'submit'
  # auto create a RecaptchaV3Rule record for the tag assigned to this field
  auto_create_rule: false
Silverstripe\Forms\Form:
  extensions:
    - 'NSWDPC\SpamProtection\FormExtension'
