---
Name: nswdpc_recaptchav3_spamprotection
---
NSWDPC\SpamProtection\RecaptchaV3TokenResponse:
  # 1 = good, 0 = spam
  score: 0.5
NSWDPC\SpamProtection\RecaptchaV3Verifier:
  # Provided by the Recaptcha admin project
  secret_key: ''
NSWDPC\SpamProtection\RecaptchaV3Field:
  # Provided by the Recaptcha admin project
  site_key: ''
  # Global action prefix for the field
  execute_action: 'submit'
  # auto create a RecaptchaV3Rule record for the tag assigned to this field
  auto_create_rule: false
Silverstripe\Forms\Form:
  extensions:
    - 'NSWDPC\SpamProtection\FormExtension'
NSWDPC\SpamProtection\RecaptchaV3SpamProtector:
  # How the badge is displayed
  # Options: '','field','form','page'
  badge_display: ''

---
Name: nswdpc_turnstile_spamprotection
---
NSWDPC\SpamProtection\TurnstileVerifier:
  # Provided by the Turnstile admin project
  secret_key: ''
NSWDPC\SpamProtection\TurnstileField:
  # Provided by the Turnstile admin project
  site_key: ''
  # Global action prefix for the field
  execute_action: 'submit'
